In [ ]:
# Install pylibCZIrw and dependencies
#! pip install --upgrade pip
#! pip install "pylibCZIrw>=3.2,<4.0" "tifffile[all]"
#! pip install czitools
#! pip install ipyfilechooser

In [1]:
from pylibCZIrw import czi as pyczi
from czitools import misc, napari_tools
from ipyfilechooser import FileChooser
from IPython.display import display, HTML
from tifffile import imread, imwrite, tiffcomment, TiffFile
import sys
import json
import os
from pathlib import Path
from czitools import misc
import numpy as np

# show the used python env
print("Using:", sys.executable)

Using: c:\Users\m1srh\Miniconda3\envs\ia39\python.exe


In [2]:
#filename = "CH=1_16bit.tif"
filename = "100x100.czi"

defaultdir = os.path.join(Path(os.getcwd()).resolve().parents[1], "data")
czifilepath = os.path.join(defaultdir, filename)
print(czifilepath)

F:\Github\czitools\data\10x10.czi


In [6]:
img2d = np.reshape(np.arange(0,100),(10,10)).astype("uint8", copy=False)
print(img2d)
print(img2d.dtype)

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]]
uint8


In [7]:
# open a new CZI and allow overwrite (!!!) to play around ...
with pyczi.create_czi(czifilepath, exist_ok=True) as czidoc_w:

    # write the plane
    czidoc_w.write(data=img2d, plane={'C':0, 'T': 0, 'Z': 0}, scene=0)
        
    # write the document title, channel names, custom attributes and XYZ scaling to the CZI file
    czidoc_w.write_metadata(
        document_name='10x10_CZI_from_TIF',
        channel_names={0: "C1"},
        scale_x=0.1 * 10 ** -6,
        scale_y=0.1 * 10 ** -6,
        scale_z=0.1 * 10 ** -6
    )